/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BotCommand : This object represents a bot command.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BotCommand {
    /// Text of the command, 1-32 characters. Can contain only lowercase English letters, digits and underscores.
    #[serde(rename = "command")]
    pub command: String,
    /// Description of the command, 3-256 characters.
    #[serde(rename = "description")]
    pub description: String,
}

impl BotCommand {
    /// This object represents a bot command.
    pub fn new(command: String, description: String) -> BotCommand {
        BotCommand {
            command,
            description,
        }
    }
}


