/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChatPhoto : This object represents a chat photo.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatPhoto {
    /// File identifier of small (160x160) chat photo. This file\\_id can be used only for photo download and only for as long as the photo is not changed.
    #[serde(rename = "small_file_id")]
    pub small_file_id: String,
    /// Unique file identifier of small (160x160) chat photo, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
    #[serde(rename = "small_file_unique_id")]
    pub small_file_unique_id: String,
    /// File identifier of big (640x640) chat photo. This file\\_id can be used only for photo download and only for as long as the photo is not changed.
    #[serde(rename = "big_file_id")]
    pub big_file_id: String,
    /// Unique file identifier of big (640x640) chat photo, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
    #[serde(rename = "big_file_unique_id")]
    pub big_file_unique_id: String,
}

impl ChatPhoto {
    /// This object represents a chat photo.
    pub fn new(small_file_id: String, small_file_unique_id: String, big_file_id: String, big_file_unique_id: String) -> ChatPhoto {
        ChatPhoto {
            small_file_id,
            small_file_unique_id,
            big_file_id,
            big_file_unique_id,
        }
    }
}


