/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChatLocation : Represents a location to which a chat is connected.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatLocation {
    #[serde(rename = "location")]
    pub location: crate::models::Location,
    /// Location address; 1-64 characters, as defined by the chat owner
    #[serde(rename = "address")]
    pub address: String,
}

impl ChatLocation {
    /// Represents a location to which a chat is connected.
    pub fn new(location: crate::models::Location, address: String) -> ChatLocation {
        ChatLocation {
            location,
            address,
        }
    }
}


