/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChatPermissions : Describes actions that a non-administrator user is allowed to take in a chat.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatPermissions {
    /// *Optional*. True, if the user is allowed to send text messages, contacts, locations and venues
    #[serde(rename = "can_send_messages", skip_serializing_if = "Option::is_none")]
    pub can_send_messages: Option<bool>,
    /// *Optional*. True, if the user is allowed to send audios, documents, photos, videos, video notes and voice notes, implies can\\_send\\_messages
    #[serde(rename = "can_send_media_messages", skip_serializing_if = "Option::is_none")]
    pub can_send_media_messages: Option<bool>,
    /// *Optional*. True, if the user is allowed to send polls, implies can\\_send\\_messages
    #[serde(rename = "can_send_polls", skip_serializing_if = "Option::is_none")]
    pub can_send_polls: Option<bool>,
    /// *Optional*. True, if the user is allowed to send animations, games, stickers and use inline bots, implies can\\_send\\_media\\_messages
    #[serde(rename = "can_send_other_messages", skip_serializing_if = "Option::is_none")]
    pub can_send_other_messages: Option<bool>,
    /// *Optional*. True, if the user is allowed to add web page previews to their messages, implies can\\_send\\_media\\_messages
    #[serde(rename = "can_add_web_page_previews", skip_serializing_if = "Option::is_none")]
    pub can_add_web_page_previews: Option<bool>,
    /// *Optional*. True, if the user is allowed to change the chat title, photo and other settings. Ignored in public supergroups
    #[serde(rename = "can_change_info", skip_serializing_if = "Option::is_none")]
    pub can_change_info: Option<bool>,
    /// *Optional*. True, if the user is allowed to invite new users to the chat
    #[serde(rename = "can_invite_users", skip_serializing_if = "Option::is_none")]
    pub can_invite_users: Option<bool>,
    /// *Optional*. True, if the user is allowed to pin messages. Ignored in public supergroups
    #[serde(rename = "can_pin_messages", skip_serializing_if = "Option::is_none")]
    pub can_pin_messages: Option<bool>,
}

impl ChatPermissions {
    /// Describes actions that a non-administrator user is allowed to take in a chat.
    pub fn new() -> ChatPermissions {
        ChatPermissions {
            can_send_messages: None,
            can_send_media_messages: None,
            can_send_polls: None,
            can_send_other_messages: None,
            can_add_web_page_previews: None,
            can_change_info: None,
            can_invite_users: None,
            can_pin_messages: None,
        }
    }
}


