/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChatMemberUpdated : This object represents changes in the status of a chat member.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatMemberUpdated {
    #[serde(rename = "chat")]
    pub chat: crate::models::Chat,
    #[serde(rename = "from")]
    pub from: crate::models::User,
    /// Date the change was done in Unix time
    #[serde(rename = "date")]
    pub date: i32,
    #[serde(rename = "old_chat_member")]
    pub old_chat_member: crate::models::ChatMember,
    #[serde(rename = "new_chat_member")]
    pub new_chat_member: crate::models::ChatMember,
    #[serde(rename = "invite_link", skip_serializing_if = "Option::is_none")]
    pub invite_link: Option<crate::models::ChatInviteLink>,
}

impl ChatMemberUpdated {
    /// This object represents changes in the status of a chat member.
    pub fn new(chat: crate::models::Chat, from: crate::models::User, date: i32, old_chat_member: crate::models::ChatMember, new_chat_member: crate::models::ChatMember) -> ChatMemberUpdated {
        ChatMemberUpdated {
            chat,
            from,
            date,
            old_chat_member,
            new_chat_member,
            invite_link: None,
        }
    }
}


