/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChatInviteLink : Represents an invite link for a chat.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatInviteLink {
    /// The invite link. If the link was created by another chat administrator, then the second part of the link will be replaced with “…”.
    #[serde(rename = "invite_link")]
    pub invite_link: String,
    #[serde(rename = "creator")]
    pub creator: crate::models::User,
    /// True, if the link is primary
    #[serde(rename = "is_primary")]
    pub is_primary: bool,
    /// True, if the link is revoked
    #[serde(rename = "is_revoked")]
    pub is_revoked: bool,
    /// *Optional*. Point in time (Unix timestamp) when the link will expire or has been expired
    #[serde(rename = "expire_date", skip_serializing_if = "Option::is_none")]
    pub expire_date: Option<i32>,
    /// *Optional*. Maximum number of users that can be members of the chat simultaneously after joining the chat via this invite link; 1-99999
    #[serde(rename = "member_limit", skip_serializing_if = "Option::is_none")]
    pub member_limit: Option<i32>,
}

impl ChatInviteLink {
    /// Represents an invite link for a chat.
    pub fn new(invite_link: String, creator: crate::models::User, is_primary: bool, is_revoked: bool) -> ChatInviteLink {
        ChatInviteLink {
            invite_link,
            creator,
            is_primary,
            is_revoked,
            expire_date: None,
            member_limit: None,
        }
    }
}


