/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "error_code")]
    pub error_code: i32,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<crate::models::ResponseParameters>,
}

impl Error {
    pub fn new(ok: bool, error_code: i32, description: String) -> Error {
        Error {
            ok,
            error_code,
            description,
            parameters: None,
        }
    }
}


