/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GameHighScore : This object represents one row of the high scores table for a game.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameHighScore {
    /// Position in high score table for the game
    #[serde(rename = "position")]
    pub position: i32,
    #[serde(rename = "user")]
    pub user: crate::models::User,
    /// Score
    #[serde(rename = "score")]
    pub score: i32,
}

impl GameHighScore {
    /// This object represents one row of the high scores table for a game.
    pub fn new(position: i32, user: crate::models::User, score: i32) -> GameHighScore {
        GameHighScore {
            position,
            user,
            score,
        }
    }
}


