/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject61 {
    /// File identifier of the sticker
    #[serde(rename = "sticker")]
    pub sticker: String,
    /// New sticker position in the set, zero-based
    #[serde(rename = "position")]
    pub position: i32,
}

impl InlineObject61 {
    pub fn new(sticker: String, position: i32) -> InlineObject61 {
        InlineObject61 {
            sticker,
            position,
        }
    }
}


