/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject43 {
    /// Unique identifier for the target chat or username of the target supergroup or channel (in the format `@channelusername`)
    #[serde(rename = "chat_id")]
    pub chat_id: crate::models::AnyOfintegerstring,
}

impl InlineObject43 {
    pub fn new(chat_id: crate::models::AnyOfintegerstring) -> InlineObject43 {
        InlineObject43 {
            chat_id,
        }
    }
}


