/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2004 {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "result")]
    pub result: crate::models::Message,
}

impl InlineResponse2004 {
    pub fn new(ok: bool, result: crate::models::Message) -> InlineResponse2004 {
        InlineResponse2004 {
            ok,
            result,
        }
    }
}


