/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject25 {
    /// Unique identifier for the target group or username of the target supergroup or channel (in the format `@username`)
    #[serde(rename = "chat_id")]
    pub chat_id: crate::models::AnyOfintegerstring,
    /// Unique identifier of the target user
    #[serde(rename = "user_id")]
    pub user_id: i32,
    /// Do nothing if the user is not banned
    #[serde(rename = "only_if_banned", skip_serializing_if = "Option::is_none")]
    pub only_if_banned: Option<bool>,
}

impl InlineObject25 {
    pub fn new(chat_id: crate::models::AnyOfintegerstring, user_id: i32) -> InlineObject25 {
        InlineObject25 {
            chat_id,
            user_id,
            only_if_banned: None,
        }
    }
}


