/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InlineQuery : This object represents an incoming inline query. When the user sends an empty query, your bot could return some default or trending results.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineQuery {
    /// Unique identifier for this query
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "from")]
    pub from: crate::models::User,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<crate::models::Location>,
    /// Text of the query (up to 256 characters)
    #[serde(rename = "query")]
    pub query: String,
    /// Offset of the results to be returned, can be controlled by the bot
    #[serde(rename = "offset")]
    pub offset: String,
}

impl InlineQuery {
    /// This object represents an incoming inline query. When the user sends an empty query, your bot could return some default or trending results.
    pub fn new(id: String, from: crate::models::User, query: String, offset: String) -> InlineQuery {
        InlineQuery {
            id,
            from,
            location: None,
            query,
            offset,
        }
    }
}


