/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject31 {
    /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`)
    #[serde(rename = "chat_id")]
    pub chat_id: crate::models::AnyOfintegerstring,
    /// Point in time (Unix timestamp) when the link will expire
    #[serde(rename = "expire_date", skip_serializing_if = "Option::is_none")]
    pub expire_date: Option<i32>,
    /// Maximum number of users that can be members of the chat simultaneously after joining the chat via this invite link; 1-99999
    #[serde(rename = "member_limit", skip_serializing_if = "Option::is_none")]
    pub member_limit: Option<i32>,
}

impl InlineObject31 {
    pub fn new(chat_id: crate::models::AnyOfintegerstring) -> InlineObject31 {
        InlineObject31 {
            chat_id,
            expire_date: None,
            member_limit: None,
        }
    }
}


