/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject68 {
    /// User identifier
    #[serde(rename = "user_id")]
    pub user_id: i32,
    /// A JSON-serialized array describing the errors
    #[serde(rename = "errors")]
    pub errors: Vec<crate::models::PassportElementError>,
}

impl InlineObject68 {
    pub fn new(user_id: i32, errors: Vec<crate::models::PassportElementError>) -> InlineObject68 {
        InlineObject68 {
            user_id,
            errors,
        }
    }
}


