/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2006 {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "result")]
    pub result: Vec<crate::models::Message>,
}

impl InlineResponse2006 {
    pub fn new(ok: bool, result: Vec<crate::models::Message>) -> InlineResponse2006 {
        InlineResponse2006 {
            ok,
            result,
        }
    }
}


