/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject4 {
    /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`)
    #[serde(rename = "chat_id")]
    pub chat_id: crate::models::AnyOfintegerstring,
    /// Unique identifier for the chat where the original message was sent (or channel username in the format `@channelusername`)
    #[serde(rename = "from_chat_id")]
    pub from_chat_id: crate::models::AnyOfintegerstring,
    /// Sends the message [silently](https://telegram.org/blog/channels-2-0#silent-messages). Users will receive a notification with no sound.
    #[serde(rename = "disable_notification", skip_serializing_if = "Option::is_none")]
    pub disable_notification: Option<bool>,
    /// Message identifier in the chat specified in *from\\_chat\\_id*
    #[serde(rename = "message_id")]
    pub message_id: i32,
}

impl InlineObject4 {
    pub fn new(chat_id: crate::models::AnyOfintegerstring, from_chat_id: crate::models::AnyOfintegerstring, message_id: i32) -> InlineObject4 {
        InlineObject4 {
            chat_id,
            from_chat_id,
            disable_notification: None,
            message_id,
        }
    }
}


