/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject38 {
    /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`)
    #[serde(rename = "chat_id")]
    pub chat_id: crate::models::AnyOfintegerstring,
    /// Identifier of a message to pin
    #[serde(rename = "message_id")]
    pub message_id: i32,
    /// Pass *True*, if it is not necessary to send a notification to all chat members about the new pinned message. Notifications are always disabled in channels and private chats.
    #[serde(rename = "disable_notification", skip_serializing_if = "Option::is_none")]
    pub disable_notification: Option<bool>,
}

impl InlineObject38 {
    pub fn new(chat_id: crate::models::AnyOfintegerstring, message_id: i32) -> InlineObject38 {
        InlineObject38 {
            chat_id,
            message_id,
            disable_notification: None,
        }
    }
}


