/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject26 {
    /// Unique identifier for the target chat or username of the target supergroup (in the format `@supergroupusername`)
    #[serde(rename = "chat_id")]
    pub chat_id: crate::models::AnyOfintegerstring,
    /// Unique identifier of the target user
    #[serde(rename = "user_id")]
    pub user_id: i32,
    #[serde(rename = "permissions")]
    pub permissions: crate::models::ChatPermissions,
    /// Date when restrictions will be lifted for the user, unix time. If user is restricted for more than 366 days or less than 30 seconds from the current time, they are considered to be restricted forever
    #[serde(rename = "until_date", skip_serializing_if = "Option::is_none")]
    pub until_date: Option<i32>,
}

impl InlineObject26 {
    pub fn new(chat_id: crate::models::AnyOfintegerstring, user_id: i32, permissions: crate::models::ChatPermissions) -> InlineObject26 {
        InlineObject26 {
            chat_id,
            user_id,
            permissions,
            until_date: None,
        }
    }
}


