/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject23 {
    /// File identifier to get info about
    #[serde(rename = "file_id")]
    pub file_id: String,
}

impl InlineObject23 {
    pub fn new(file_id: String) -> InlineObject23 {
        InlineObject23 {
            file_id,
        }
    }
}


