/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject29 {
    /// Unique identifier for the target chat or username of the target supergroup (in the format `@supergroupusername`)
    #[serde(rename = "chat_id")]
    pub chat_id: crate::models::AnyOfintegerstring,
    #[serde(rename = "permissions")]
    pub permissions: crate::models::ChatPermissions,
}

impl InlineObject29 {
    pub fn new(chat_id: crate::models::AnyOfintegerstring, permissions: crate::models::ChatPermissions) -> InlineObject29 {
        InlineObject29 {
            chat_id,
            permissions,
        }
    }
}


