/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2008 {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "result")]
    pub result: crate::models::UserProfilePhotos,
}

impl InlineResponse2008 {
    pub fn new(ok: bool, result: crate::models::UserProfilePhotos) -> InlineResponse2008 {
        InlineResponse2008 {
            ok,
            result,
        }
    }
}


