/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject49 {
    /// A JSON-serialized list of bot commands to be set as the list of the bot's commands. At most 100 commands can be specified.
    #[serde(rename = "commands")]
    pub commands: Vec<crate::models::BotCommand>,
}

impl InlineObject49 {
    pub fn new(commands: Vec<crate::models::BotCommand>) -> InlineObject49 {
        InlineObject49 {
            commands,
        }
    }
}


