/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject46 {
    /// Unique identifier for the target chat or username of the target supergroup (in the format `@supergroupusername`)
    #[serde(rename = "chat_id")]
    pub chat_id: crate::models::AnyOfintegerstring,
    /// Name of the sticker set to be set as the group sticker set
    #[serde(rename = "sticker_set_name")]
    pub sticker_set_name: String,
}

impl InlineObject46 {
    pub fn new(chat_id: crate::models::AnyOfintegerstring, sticker_set_name: String) -> InlineObject46 {
        InlineObject46 {
            chat_id,
            sticker_set_name,
        }
    }
}


