/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject36 {
    /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`)
    #[serde(rename = "chat_id")]
    pub chat_id: crate::models::AnyOfintegerstring,
    /// New chat title, 1-255 characters
    #[serde(rename = "title")]
    pub title: String,
}

impl InlineObject36 {
    pub fn new(chat_id: crate::models::AnyOfintegerstring, title: String) -> InlineObject36 {
        InlineObject36 {
            chat_id,
            title,
        }
    }
}


