/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject22 {
    /// Unique identifier of the target user
    #[serde(rename = "user_id")]
    pub user_id: i32,
    /// Sequential number of the first photo to be returned. By default, all photos are returned.
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    /// Limits the number of photos to be retrieved. Values between 1-100 are accepted. Defaults to 100.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

impl InlineObject22 {
    pub fn new(user_id: i32) -> InlineObject22 {
        InlineObject22 {
            user_id,
            offset: None,
            limit: None,
        }
    }
}


