/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject45 {
    /// Unique identifier for the target chat or username of the target supergroup or channel (in the format `@channelusername`)
    #[serde(rename = "chat_id")]
    pub chat_id: crate::models::AnyOfintegerstring,
    /// Unique identifier of the target user
    #[serde(rename = "user_id")]
    pub user_id: i32,
}

impl InlineObject45 {
    pub fn new(chat_id: crate::models::AnyOfintegerstring, user_id: i32) -> InlineObject45 {
        InlineObject45 {
            chat_id,
            user_id,
        }
    }
}


