/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject67 {
    /// Unique identifier for the query to be answered
    #[serde(rename = "pre_checkout_query_id")]
    pub pre_checkout_query_id: String,
    /// Specify *True* if everything is alright (goods are available, etc.) and the bot is ready to proceed with the order. Use *False* if there are any problems.
    #[serde(rename = "ok")]
    pub ok: bool,
    /// Required if *ok* is *False*. Error message in human readable form that explains the reason for failure to proceed with the checkout (e.g. \"Sorry, somebody just bought the last of our amazing black T-shirts while you were busy filling out your payment details. Please choose a different color or garment!\"). Telegram will display this message to the user.
    #[serde(rename = "error_message", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
}

impl InlineObject67 {
    pub fn new(pre_checkout_query_id: String, ok: bool) -> InlineObject67 {
        InlineObject67 {
            pre_checkout_query_id,
            ok,
            error_message: None,
        }
    }
}


