/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject71 {
    /// Target user id
    #[serde(rename = "user_id")]
    pub user_id: i32,
    /// Required if *inline\\_message\\_id* is not specified. Unique identifier for the target chat
    #[serde(rename = "chat_id", skip_serializing_if = "Option::is_none")]
    pub chat_id: Option<i32>,
    /// Required if *inline\\_message\\_id* is not specified. Identifier of the sent message
    #[serde(rename = "message_id", skip_serializing_if = "Option::is_none")]
    pub message_id: Option<i32>,
    /// Required if *chat\\_id* and *message\\_id* are not specified. Identifier of the inline message
    #[serde(rename = "inline_message_id", skip_serializing_if = "Option::is_none")]
    pub inline_message_id: Option<String>,
}

impl InlineObject71 {
    pub fn new(user_id: i32) -> InlineObject71 {
        InlineObject71 {
            user_id,
            chat_id: None,
            message_id: None,
            inline_message_id: None,
        }
    }
}


