/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject54 {
    /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`)
    #[serde(rename = "chat_id")]
    pub chat_id: crate::models::AnyOfintegerstring,
    /// Identifier of the original message with the poll
    #[serde(rename = "message_id")]
    pub message_id: i32,
    #[serde(rename = "reply_markup", skip_serializing_if = "Option::is_none")]
    pub reply_markup: Option<crate::models::InlineKeyboardMarkup>,
}

impl InlineObject54 {
    pub fn new(chat_id: crate::models::AnyOfintegerstring, message_id: i32) -> InlineObject54 {
        InlineObject54 {
            chat_id,
            message_id,
            reply_markup: None,
        }
    }
}


