/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject62 {
    /// File identifier of the sticker
    #[serde(rename = "sticker")]
    pub sticker: String,
}

impl InlineObject62 {
    pub fn new(sticker: String) -> InlineObject62 {
        InlineObject62 {
            sticker,
        }
    }
}


