/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject33 {
    /// Unique identifier of the target chat or username of the target channel (in the format `@channelusername`)
    #[serde(rename = "chat_id")]
    pub chat_id: crate::models::AnyOfintegerstring,
    /// The invite link to revoke
    #[serde(rename = "invite_link")]
    pub invite_link: String,
}

impl InlineObject33 {
    pub fn new(chat_id: crate::models::AnyOfintegerstring, invite_link: String) -> InlineObject33 {
        InlineObject33 {
            chat_id,
            invite_link,
        }
    }
}


