/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject57 {
    /// Name of the sticker set
    #[serde(rename = "name")]
    pub name: String,
}

impl InlineObject57 {
    pub fn new(name: String) -> InlineObject57 {
        InlineObject57 {
            name,
        }
    }
}


