/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject28 {
    /// Unique identifier for the target chat or username of the target supergroup (in the format `@supergroupusername`)
    #[serde(rename = "chat_id")]
    pub chat_id: crate::models::AnyOfintegerstring,
    /// Unique identifier of the target user
    #[serde(rename = "user_id")]
    pub user_id: i32,
    /// New custom title for the administrator; 0-16 characters, emoji are not allowed
    #[serde(rename = "custom_title")]
    pub custom_title: String,
}

impl InlineObject28 {
    pub fn new(chat_id: crate::models::AnyOfintegerstring, user_id: i32, custom_title: String) -> InlineObject28 {
        InlineObject28 {
            chat_id,
            user_id,
            custom_title,
        }
    }
}


