/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Invoice : This object contains basic information about an invoice.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Invoice {
    /// Product name
    #[serde(rename = "title")]
    pub title: String,
    /// Product description
    #[serde(rename = "description")]
    pub description: String,
    /// Unique bot deep-linking parameter that can be used to generate this invoice
    #[serde(rename = "start_parameter")]
    pub start_parameter: String,
    /// Three-letter ISO 4217 [currency](/bots/payments#supported-currencies) code
    #[serde(rename = "currency")]
    pub currency: String,
    /// Total price in the *smallest units* of the currency (integer, **not** float/double). For example, for a price of `US$ 1.45` pass `amount = 145`. See the *exp* parameter in [currencies.json](https://core.telegram.org/bots/payments/currencies.json), it shows the number of digits past the decimal point for each currency (2 for the majority of currencies).
    #[serde(rename = "total_amount")]
    pub total_amount: i32,
}

impl Invoice {
    /// This object contains basic information about an invoice.
    pub fn new(title: String, description: String, start_parameter: String, currency: String, total_amount: i32) -> Invoice {
        Invoice {
            title,
            description,
            start_parameter,
            currency,
            total_amount,
        }
    }
}


