/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Location : This object represents a point on the map.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Location {
    /// Longitude as defined by sender
    #[serde(rename = "longitude")]
    pub longitude: f32,
    /// Latitude as defined by sender
    #[serde(rename = "latitude")]
    pub latitude: f32,
    /// *Optional*. The radius of uncertainty for the location, measured in meters; 0-1500
    #[serde(rename = "horizontal_accuracy", skip_serializing_if = "Option::is_none")]
    pub horizontal_accuracy: Option<f32>,
    /// *Optional*. Time relative to the message sending date, during which the location can be updated, in seconds. For active live locations only.
    #[serde(rename = "live_period", skip_serializing_if = "Option::is_none")]
    pub live_period: Option<i32>,
    /// *Optional*. The direction in which user is moving, in degrees; 1-360. For active live locations only.
    #[serde(rename = "heading", skip_serializing_if = "Option::is_none")]
    pub heading: Option<i32>,
    /// *Optional*. Maximum distance for proximity alerts about approaching another chat member, in meters. For sent live locations only.
    #[serde(rename = "proximity_alert_radius", skip_serializing_if = "Option::is_none")]
    pub proximity_alert_radius: Option<i32>,
}

impl Location {
    /// This object represents a point on the map.
    pub fn new(longitude: f32, latitude: f32) -> Location {
        Location {
            longitude,
            latitude,
            horizontal_accuracy: None,
            live_period: None,
            heading: None,
            proximity_alert_radius: None,
        }
    }
}


