/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MaskPosition : This object describes the position on faces where a mask should be placed by default.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaskPosition {
    /// The part of the face relative to which the mask should be placed. One of “forehead”, “eyes”, “mouth”, or “chin”.
    #[serde(rename = "point")]
    pub point: Point,
    /// Shift by X-axis measured in widths of the mask scaled to the face size, from left to right. For example, choosing -1.0 will place mask just to the left of the default mask position.
    #[serde(rename = "x_shift")]
    pub x_shift: f32,
    /// Shift by Y-axis measured in heights of the mask scaled to the face size, from top to bottom. For example, 1.0 will place the mask just below the default mask position.
    #[serde(rename = "y_shift")]
    pub y_shift: f32,
    /// Mask scaling coefficient. For example, 2.0 means double size.
    #[serde(rename = "scale")]
    pub scale: f32,
}

impl MaskPosition {
    /// This object describes the position on faces where a mask should be placed by default.
    pub fn new(point: Point, x_shift: f32, y_shift: f32, scale: f32) -> MaskPosition {
        MaskPosition {
            point,
            x_shift,
            y_shift,
            scale,
        }
    }
}

/// The part of the face relative to which the mask should be placed. One of “forehead”, “eyes”, “mouth”, or “chin”.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Point {
    #[serde(rename = "forehead")]
    Forehead,
    #[serde(rename = "eyes")]
    Eyes,
    #[serde(rename = "mouth")]
    Mouth,
    #[serde(rename = "chin")]
    Chin,
}

