/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MessageId : This object represents a unique message identifier.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageId {
    /// Unique message identifier
    #[serde(rename = "message_id")]
    pub message_id: i32,
}

impl MessageId {
    /// This object represents a unique message identifier.
    pub fn new(message_id: i32) -> MessageId {
        MessageId {
            message_id,
        }
    }
}


