/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MessageAutoDeleteTimerChanged : This object represents a service message about a change in auto-delete timer settings.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageAutoDeleteTimerChanged {
    /// New auto-delete time for messages in the chat
    #[serde(rename = "message_auto_delete_time")]
    pub message_auto_delete_time: i32,
}

impl MessageAutoDeleteTimerChanged {
    /// This object represents a service message about a change in auto-delete timer settings.
    pub fn new(message_auto_delete_time: i32) -> MessageAutoDeleteTimerChanged {
        MessageAutoDeleteTimerChanged {
            message_auto_delete_time,
        }
    }
}


