/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// OrderInfo : This object represents information about an order.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderInfo {
    /// *Optional*. User name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// *Optional*. User's phone number
    #[serde(rename = "phone_number", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    /// *Optional*. User email
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "shipping_address", skip_serializing_if = "Option::is_none")]
    pub shipping_address: Option<crate::models::ShippingAddress>,
}

impl OrderInfo {
    /// This object represents information about an order.
    pub fn new() -> OrderInfo {
        OrderInfo {
            name: None,
            phone_number: None,
            email: None,
            shipping_address: None,
        }
    }
}


