/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PassportData : Contains information about Telegram Passport data shared with the bot by the user.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PassportData {
    /// Array with information about documents and other Telegram Passport elements that was shared with the bot
    #[serde(rename = "data")]
    pub data: Vec<crate::models::EncryptedPassportElement>,
    #[serde(rename = "credentials")]
    pub credentials: crate::models::EncryptedCredentials,
}

impl PassportData {
    /// Contains information about Telegram Passport data shared with the bot by the user.
    pub fn new(data: Vec<crate::models::EncryptedPassportElement>, credentials: crate::models::EncryptedCredentials) -> PassportData {
        PassportData {
            data,
            credentials,
        }
    }
}


