/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PassportFile : This object represents a file uploaded to Telegram Passport. Currently all Telegram Passport files are in JPEG format when decrypted and don't exceed 10MB.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PassportFile {
    /// Identifier for this file, which can be used to download or reuse the file
    #[serde(rename = "file_id")]
    pub file_id: String,
    /// Unique identifier for this file, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
    #[serde(rename = "file_unique_id")]
    pub file_unique_id: String,
    /// File size
    #[serde(rename = "file_size")]
    pub file_size: i32,
    /// Unix time when the file was uploaded
    #[serde(rename = "file_date")]
    pub file_date: i32,
}

impl PassportFile {
    /// This object represents a file uploaded to Telegram Passport. Currently all Telegram Passport files are in JPEG format when decrypted and don't exceed 10MB.
    pub fn new(file_id: String, file_unique_id: String, file_size: i32, file_date: i32) -> PassportFile {
        PassportFile {
            file_id,
            file_unique_id,
            file_size,
            file_date,
        }
    }
}


