/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PhotoSize : This object represents one size of a photo or a [file](https://core.telegram.org/bots/api/#document) / [sticker](https://core.telegram.org/bots/api/#sticker) thumbnail.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PhotoSize {
    /// Identifier for this file, which can be used to download or reuse the file
    #[serde(rename = "file_id")]
    pub file_id: String,
    /// Unique identifier for this file, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
    #[serde(rename = "file_unique_id")]
    pub file_unique_id: String,
    /// Photo width
    #[serde(rename = "width")]
    pub width: i32,
    /// Photo height
    #[serde(rename = "height")]
    pub height: i32,
    /// *Optional*. File size
    #[serde(rename = "file_size", skip_serializing_if = "Option::is_none")]
    pub file_size: Option<i32>,
}

impl PhotoSize {
    /// This object represents one size of a photo or a [file](https://core.telegram.org/bots/api/#document) / [sticker](https://core.telegram.org/bots/api/#sticker) thumbnail.
    pub fn new(file_id: String, file_unique_id: String, width: i32, height: i32) -> PhotoSize {
        PhotoSize {
            file_id,
            file_unique_id,
            width,
            height,
            file_size: None,
        }
    }
}


