/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PollAnswer : This object represents an answer of a user in a non-anonymous poll.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PollAnswer {
    /// Unique poll identifier
    #[serde(rename = "poll_id")]
    pub poll_id: String,
    #[serde(rename = "user")]
    pub user: crate::models::User,
    /// 0-based identifiers of answer options, chosen by the user. May be empty if the user retracted their vote.
    #[serde(rename = "option_ids")]
    pub option_ids: Vec<i32>,
}

impl PollAnswer {
    /// This object represents an answer of a user in a non-anonymous poll.
    pub fn new(poll_id: String, user: crate::models::User, option_ids: Vec<i32>) -> PollAnswer {
        PollAnswer {
            poll_id,
            user,
            option_ids,
        }
    }
}


