/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PollOption : This object contains information about one answer option in a poll.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PollOption {
    /// Option text, 1-100 characters
    #[serde(rename = "text")]
    pub text: String,
    /// Number of users that voted for this option
    #[serde(rename = "voter_count")]
    pub voter_count: i32,
}

impl PollOption {
    /// This object contains information about one answer option in a poll.
    pub fn new(text: String, voter_count: i32) -> PollOption {
        PollOption {
            text,
            voter_count,
        }
    }
}


