/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProximityAlertTriggered : This object represents the content of a service message, sent whenever a user in the chat triggers a proximity alert set by another user.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProximityAlertTriggered {
    #[serde(rename = "traveler")]
    pub traveler: crate::models::User,
    #[serde(rename = "watcher")]
    pub watcher: crate::models::User,
    /// The distance between the users
    #[serde(rename = "distance")]
    pub distance: i32,
}

impl ProximityAlertTriggered {
    /// This object represents the content of a service message, sent whenever a user in the chat triggers a proximity alert set by another user.
    pub fn new(traveler: crate::models::User, watcher: crate::models::User, distance: i32) -> ProximityAlertTriggered {
        ProximityAlertTriggered {
            traveler,
            watcher,
            distance,
        }
    }
}


