/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ResponseParameters : Contains information about why a request was unsuccessful.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseParameters {
    /// *Optional*. The group has been migrated to a supergroup with the specified identifier. This number may have more than 32 significant bits and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a signed 64-bit integer or double-precision float type are safe for storing this identifier.
    #[serde(rename = "migrate_to_chat_id", skip_serializing_if = "Option::is_none")]
    pub migrate_to_chat_id: Option<i32>,
    /// *Optional*. In case of exceeding flood control, the number of seconds left to wait before the request can be repeated
    #[serde(rename = "retry_after", skip_serializing_if = "Option::is_none")]
    pub retry_after: Option<i32>,
}

impl ResponseParameters {
    /// Contains information about why a request was unsuccessful.
    pub fn new() -> ResponseParameters {
        ResponseParameters {
            migrate_to_chat_id: None,
            retry_after: None,
        }
    }
}


