/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ShippingAddress : This object represents a shipping address.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShippingAddress {
    /// ISO 3166-1 alpha-2 country code
    #[serde(rename = "country_code")]
    pub country_code: String,
    /// State, if applicable
    #[serde(rename = "state")]
    pub state: String,
    /// City
    #[serde(rename = "city")]
    pub city: String,
    /// First line for the address
    #[serde(rename = "street_line1")]
    pub street_line1: String,
    /// Second line for the address
    #[serde(rename = "street_line2")]
    pub street_line2: String,
    /// Address post code
    #[serde(rename = "post_code")]
    pub post_code: String,
}

impl ShippingAddress {
    /// This object represents a shipping address.
    pub fn new(country_code: String, state: String, city: String, street_line1: String, street_line2: String, post_code: String) -> ShippingAddress {
        ShippingAddress {
            country_code,
            state,
            city,
            street_line1,
            street_line2,
            post_code,
        }
    }
}


