/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ShippingQuery : This object contains information about an incoming shipping query.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShippingQuery {
    /// Unique query identifier
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "from")]
    pub from: crate::models::User,
    /// Bot specified invoice payload
    #[serde(rename = "invoice_payload")]
    pub invoice_payload: String,
    #[serde(rename = "shipping_address")]
    pub shipping_address: crate::models::ShippingAddress,
}

impl ShippingQuery {
    /// This object contains information about an incoming shipping query.
    pub fn new(id: String, from: crate::models::User, invoice_payload: String, shipping_address: crate::models::ShippingAddress) -> ShippingQuery {
        ShippingQuery {
            id,
            from,
            invoice_payload,
            shipping_address,
        }
    }
}


