/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Sticker : This object represents a sticker.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Sticker {
    /// Identifier for this file, which can be used to download or reuse the file
    #[serde(rename = "file_id")]
    pub file_id: String,
    /// Unique identifier for this file, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
    #[serde(rename = "file_unique_id")]
    pub file_unique_id: String,
    /// Sticker width
    #[serde(rename = "width")]
    pub width: i32,
    /// Sticker height
    #[serde(rename = "height")]
    pub height: i32,
    /// *True*, if the sticker is [animated](https://telegram.org/blog/animated-stickers)
    #[serde(rename = "is_animated")]
    pub is_animated: bool,
    #[serde(rename = "thumb", skip_serializing_if = "Option::is_none")]
    pub thumb: Option<crate::models::PhotoSize>,
    /// *Optional*. Emoji associated with the sticker
    #[serde(rename = "emoji", skip_serializing_if = "Option::is_none")]
    pub emoji: Option<String>,
    /// *Optional*. Name of the sticker set to which the sticker belongs
    #[serde(rename = "set_name", skip_serializing_if = "Option::is_none")]
    pub set_name: Option<String>,
    #[serde(rename = "mask_position", skip_serializing_if = "Option::is_none")]
    pub mask_position: Option<crate::models::MaskPosition>,
    /// *Optional*. File size
    #[serde(rename = "file_size", skip_serializing_if = "Option::is_none")]
    pub file_size: Option<i32>,
}

impl Sticker {
    /// This object represents a sticker.
    pub fn new(file_id: String, file_unique_id: String, width: i32, height: i32, is_animated: bool) -> Sticker {
        Sticker {
            file_id,
            file_unique_id,
            width,
            height,
            is_animated,
            thumb: None,
            emoji: None,
            set_name: None,
            mask_position: None,
            file_size: None,
        }
    }
}


