/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UserProfilePhotos : This object represent a user's profile pictures.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserProfilePhotos {
    /// Total number of profile pictures the target user has
    #[serde(rename = "total_count")]
    pub total_count: i32,
    /// Requested profile pictures (in up to 4 sizes each)
    #[serde(rename = "photos")]
    pub photos: Vec<Vec<crate::models::PhotoSize>>,
}

impl UserProfilePhotos {
    /// This object represent a user's profile pictures.
    pub fn new(total_count: i32, photos: Vec<Vec<crate::models::PhotoSize>>) -> UserProfilePhotos {
        UserProfilePhotos {
            total_count,
            photos,
        }
    }
}


