/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Video : This object represents a video file.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Video {
    /// Identifier for this file, which can be used to download or reuse the file
    #[serde(rename = "file_id")]
    pub file_id: String,
    /// Unique identifier for this file, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
    #[serde(rename = "file_unique_id")]
    pub file_unique_id: String,
    /// Video width as defined by sender
    #[serde(rename = "width")]
    pub width: i32,
    /// Video height as defined by sender
    #[serde(rename = "height")]
    pub height: i32,
    /// Duration of the video in seconds as defined by sender
    #[serde(rename = "duration")]
    pub duration: i32,
    #[serde(rename = "thumb", skip_serializing_if = "Option::is_none")]
    pub thumb: Option<crate::models::PhotoSize>,
    /// *Optional*. Original filename as defined by sender
    #[serde(rename = "file_name", skip_serializing_if = "Option::is_none")]
    pub file_name: Option<String>,
    /// *Optional*. Mime type of a file as defined by sender
    #[serde(rename = "mime_type", skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    /// *Optional*. File size
    #[serde(rename = "file_size", skip_serializing_if = "Option::is_none")]
    pub file_size: Option<i32>,
}

impl Video {
    /// This object represents a video file.
    pub fn new(file_id: String, file_unique_id: String, width: i32, height: i32, duration: i32) -> Video {
        Video {
            file_id,
            file_unique_id,
            width,
            height,
            duration,
            thumb: None,
            file_name: None,
            mime_type: None,
            file_size: None,
        }
    }
}


