/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VoiceChatEnded : This object represents a service message about a voice chat ended in the chat.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VoiceChatEnded {
    /// Voice chat duration; in seconds
    #[serde(rename = "duration")]
    pub duration: i32,
}

impl VoiceChatEnded {
    /// This object represents a service message about a voice chat ended in the chat.
    pub fn new(duration: i32) -> VoiceChatEnded {
        VoiceChatEnded {
            duration,
        }
    }
}


