/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Voice : This object represents a voice note.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Voice {
    /// Identifier for this file, which can be used to download or reuse the file
    #[serde(rename = "file_id")]
    pub file_id: String,
    /// Unique identifier for this file, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
    #[serde(rename = "file_unique_id")]
    pub file_unique_id: String,
    /// Duration of the audio in seconds as defined by sender
    #[serde(rename = "duration")]
    pub duration: i32,
    /// *Optional*. MIME type of the file as defined by sender
    #[serde(rename = "mime_type", skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    /// *Optional*. File size
    #[serde(rename = "file_size", skip_serializing_if = "Option::is_none")]
    pub file_size: Option<i32>,
}

impl Voice {
    /// This object represents a voice note.
    pub fn new(file_id: String, file_unique_id: String, duration: i32) -> Voice {
        Voice {
            file_id,
            file_unique_id,
            duration,
            mime_type: None,
            file_size: None,
        }
    }
}


