/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VoiceChatParticipantsInvited : This object represents a service message about new members invited to a voice chat.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VoiceChatParticipantsInvited {
    /// *Optional*. New members that were invited to the voice chat
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<crate::models::User>>,
}

impl VoiceChatParticipantsInvited {
    /// This object represents a service message about new members invited to a voice chat.
    pub fn new() -> VoiceChatParticipantsInvited {
        VoiceChatParticipantsInvited {
            users: None,
        }
    }
}


