/*
 * Telegram Bot API
 *
 * Auto-generated OpenAPI schema
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WebhookInfo : Contains information about the current status of a webhook.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookInfo {
    /// Webhook URL, may be empty if webhook is not set up
    #[serde(rename = "url")]
    pub url: String,
    /// True, if a custom certificate was provided for webhook certificate checks
    #[serde(rename = "has_custom_certificate")]
    pub has_custom_certificate: bool,
    /// Number of updates awaiting delivery
    #[serde(rename = "pending_update_count")]
    pub pending_update_count: i32,
    /// *Optional*. Currently used webhook IP address
    #[serde(rename = "ip_address", skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    /// *Optional*. Unix time for the most recent error that happened when trying to deliver an update via webhook
    #[serde(rename = "last_error_date", skip_serializing_if = "Option::is_none")]
    pub last_error_date: Option<i32>,
    /// *Optional*. Error message in human-readable format for the most recent error that happened when trying to deliver an update via webhook
    #[serde(rename = "last_error_message", skip_serializing_if = "Option::is_none")]
    pub last_error_message: Option<String>,
    /// *Optional*. Maximum allowed number of simultaneous HTTPS connections to the webhook for update delivery
    #[serde(rename = "max_connections", skip_serializing_if = "Option::is_none")]
    pub max_connections: Option<i32>,
    /// *Optional*. A list of update types the bot is subscribed to. Defaults to all update types except *chat\\_member*
    #[serde(rename = "allowed_updates", skip_serializing_if = "Option::is_none")]
    pub allowed_updates: Option<Vec<String>>,
}

impl WebhookInfo {
    /// Contains information about the current status of a webhook.
    pub fn new(url: String, has_custom_certificate: bool, pending_update_count: i32) -> WebhookInfo {
        WebhookInfo {
            url,
            has_custom_certificate,
            pending_update_count,
            ip_address: None,
            last_error_date: None,
            last_error_message: None,
            max_connections: None,
            allowed_updates: None,
        }
    }
}


